### ISSUE TITLE
Possible SIGBUS in `device_event_record` with OpenCL

### ISSUE THREAD

**Issue by njansson** [ExtremeFLOW/neko#1052]

**Comment by njansson** [comment]
Ensure that the opaque pointer is initialised with `C_NULL_PTR` seems to resolve the issue in a small reproducer code

```fortran
program test
  use neko
  use device
  use, intrinsic :: iso_c_binding

  type(c_ptr) :: w = C_NULL_PTR

  call neko_init

  call device_event_record(w, glb_cmd_queue)

  call device_event_sync(w)

end program test
```

**Comment by njansson** [comment]
Without `C_NULL_PTR` the following error is thrown

```shell
    _  __  ____  __ __  ____
   / |/ / / __/ / //_/ / __ \
  /    / / _/  / ,<   / /_/ /
 /_/|_/ /___/ /_/|_|  \____/

 (version: 0.7.0-rc1)
 (build: 2023-12-01 on x86_64-apple-darwin21.6.0 using gnu)


Program received signal SIGBUS: Access to an undefined portion of a memory object.

Backtrace for this error:
#0  0x104150cb2 in ???
#1  0x10414febd in ???
#2  0x7ff81fb28dfc in ???
#3  0x7ffa39f5179a in ???
#4  0x7ffa39f2d89c in ???
#5  0x10352e123 in __device_MOD_device_event_record
	at device/device.F90:1252
#6  0x103562f43 in main
	at /tmp/test.f90:10
Bus error
```
