### ISSUE TITLE
Segmentation fault of `rea2nbin`

### ISSUE THREAD

**Issue by timfelle** [ExtremeFLOW/neko#1470]
The updated boundary conditions seem to cause issues when converting from `re2` to `nbin`.

<details>
<summary>Output message</summary>

```
    _  __  ____  __ __  ____  
   / |/ / / __/ / //_/ / __ \ 
  /    / / _/  / ,<   / /_/ / 
 /_/|_/ /___/ /_/|_|  \____/  
 
 (version: 0.8.99)
 (build: 2024-09-09 on x86_64-pc-linux-gnu using gnu)
 
 Reading binary NEKTON file debugging_pipe.re2
 gdim = 3, nelements =    160
 *** WARNING: No NEKTON map file found  ***
           1 elements read
           2 elements read
           3 elements read
           4 elements read
           5 elements read
           6 elements read
           7 elements read
           8 elements read
           9 elements read
          10 elements read
          11 elements read
          12 elements read
          13 elements read
          14 elements read
          15 elements read
          16 elements read
          17 elements read
          18 elements read
          19 elements read
          20 elements read
          21 elements read
          22 elements read
          23 elements read
          24 elements read
          25 elements read
          26 elements read
          27 elements read
          28 elements read
          29 elements read
          30 elements read
          31 elements read
          32 elements read
          33 elements read
          34 elements read
          35 elements read
          36 elements read
          37 elements read
          38 elements read
          39 elements read
          40 elements read
          41 elements read
          42 elements read
          43 elements read
          44 elements read
          45 elements read
          46 elements read
          47 elements read
          48 elements read
          49 elements read
          50 elements read
          51 elements read
          52 elements read
          53 elements read
          54 elements read
          55 elements read
          56 elements read
          57 elements read
          58 elements read
          59 elements read
          60 elements read
          61 elements read
          62 elements read
          63 elements read
          64 elements read
          65 elements read
          66 elements read
          67 elements read
          68 elements read
          69 elements read
          70 elements read
          71 elements read
          72 elements read
          73 elements read
          74 elements read
          75 elements read
          76 elements read
          77 elements read
          78 elements read
          79 elements read
          80 elements read
          81 elements read
          82 elements read
          83 elements read
          84 elements read
          85 elements read
          86 elements read
          87 elements read
          88 elements read
          89 elements read
          90 elements read
          91 elements read
          92 elements read
          93 elements read
          94 elements read
          95 elements read
          96 elements read
          97 elements read
          98 elements read
          99 elements read
         100 elements read
         101 elements read
         102 elements read
         103 elements read
         104 elements read
         105 elements read
         106 elements read
         107 elements read
         108 elements read
         109 elements read
         110 elements read
         111 elements read
         112 elements read
         113 elements read
         114 elements read
         115 elements read
         116 elements read
         117 elements read
         118 elements read
         119 elements read
         120 elements read
         121 elements read
         122 elements read
         123 elements read
         124 elements read
         125 elements read
         126 elements read
         127 elements read
         128 elements read
         129 elements read
         130 elements read
         131 elements read
         132 elements read
         133 elements read
         134 elements read
         135 elements read
         136 elements read
         137 elements read
         138 elements read
         139 elements read
         140 elements read
```
</details>

<details>
<summary>Error message</summary>

```
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7f7c316de960 in ???
#1  0x7f7c316ddac5 in ???
#2  0x7f7c313cd51f in ???
	at ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
#3  0x7f7c3152b815 in ???
	at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:383
#4  0x7f7c3194028e in ???
#5  0x7f7c319412e5 in ???
#6  0x55ac4ff595a1 in re2_file_read_bcs
	at io/re2_file.f90:685
#7  0x55ac4ff5a8c2 in __re2_file_MOD_re2_file_read
	at io/re2_file.f90:196
#8  0x55ac4ff42428 in __file_MOD_file_read
	at io/file.f90:163
#9  0x55ac4ff2cfdd in rea2nbin
	at neko/contrib/rea2nbin/rea2nbin.f90:38
#10  0x55ac4ff2cade in main
	at neko/contrib/rea2nbin/rea2nbin.f90:2
```
</details>

**Comment by MartinKarp** [comment]
This is resolved now or?

**Comment by timfelle** [comment]
Ah yes it is
